pages/urls.py
from django.conf.urls import url
from . import views

app_name = 'pages'
urlpatterns = [
    url(r'^$',              views.home,                name='index'),
    url(r'^home/$',         views.home,                name='home'),
    url(r'^about/$',        views.about,               name='about'),
    url(r'^contact/$',      views.contact,             name='contact'),
    url(r'^work/$',         views.work,                name='work'),
    url(r'^testimonials/$', views.testimonials,        name='testimonials')
]

pages/templates/pages/about.html
{% extends "pages/base.html" %}
{% load static %}

{% block content %}
  <!-- Company & Equipment -->
  <div class="row gwm-mt gwm-mb">
    
    <!-- Company -->
    <div class="col-md-5 col-md-offset-1
                col-xs-12">
      
      <h2 class="gwm-header2 gwm-text-left">
        <span class="gwm-letter">O</span>ur Company at a Glance
      </h2>
      
      <div class="row">
        
        <div class="col-md-12
                    col-xs-12">
          <img class="profile" src="{% static 'images/profile.png' %}">
        </div>
        
        <div class="col-md-12
                    col-xs-12">
          <p class="gwm-text gwm-text-left">
            <i class="fa fa-user"></i>
            Carlos Gonzalez - Owner <br>
            Here at Gonzalez Welding Mobile, we are dedicated to you and your welding needs. I have been welding since 1993 for various companies and have worked side jobs involving commercial and residential projects. I provided superior service to my customers and I am currently certified to weld Stick, Mig and Tig (Mild steel, Stainless Steel and Aluminum) and also certified with D1.1, D1.5 wire NR-232 and core8, Dual Shield, E7018, Pipe 6G and ER5356 and more procedures.
          </p>
        </div>
        
      </div>
      
    </div>
    <!-- End Company-->
    
    <!-- Equipment -->
    <div class="gwm-text-left 
                col-md-4 col-md-offset-1
                col-xs-12">
      
      <h2 class="gwm-header2">
        <span class="gwm-letter">E</span>quipment
      </h2>
      
      <div class="row">
        
        <div class="col-md-6">
          
          <h3 class="gwm-header3">Miller</h3>
          <p>Trailblazer 302</p>
          <p>Millermatic 252</p>
          <p>Dynasty 280 DX</p>
          <p>XR-D with Aumna Pro</p>
          <p>Maxtar 150 STL</p>
          <p>30 A Spool Gun</p>
          
        </div>
        
        <div class="col-md-6">
          
          <h3 class="gwm-header3">Lincoln</h3>
          <p>Vantage 500</p>
          <p>Ln 25 Wire Feeder</p>
          <p>Power Mig 140c</p>
          
        </div>
        
      </div>
      
      <h3 class="gwm-header3">
        Hypertherm 30 Plasma Cutter
      </h3>
      
      <i>
        Equipment is essential in getting the job done but it takes skill to get the job done right.
      </i>
      
    </div>
    <!-- End Equipment -->
    
  </div>
  <!-- End Company & Equipment --> 
  
  <!-- Work History -->
  <div class="row gwm-text-left">
    <!-- Work History Column -->
    <div class="col-md-10 col-md-offset-1">
      
      <h2 class="gwm-header2">
        <span class="gwm-letter">B</span>rief Work History
      </h2>
      
      <!-- Well -->
      <div class="well gwm-well">
        
        <div>
          <h3 class="gwm-header3">
            1993-2000
          </h3>
          <p>
            Bay Ship & Yacht, started as a labor and soon after started welding. My positions were production welding and a lead-man. I lead other welders in carrying out their job, which involved supervising and assuring that the work was done right.
          </p>
        </div>
        
        <div>
          <h3 class="gwm-header3">
            2000-2001
          </h3>
          <p>
            Masters Tug and Tow, Junior Deck Engineer, my work included maintaining tugs structurally and mechanical while assisting on the deck.
          </p>
        </div>
        
        <div>
          <h3 class="gwm-header3">
            2001-2005
          </h3>
          <p>
            Tutor Saliva, Production Welder "Journeyman", welded new columns, cofferdams, wailer systems, sheet piles, pipe piles and beam piles.
          </p>
        </div>
        
        <div>
          <h3 class="gwm-header3">
            2005-2012
          </h3>
          <p>
            Salt River Construction, Lead Welder and Foreman, was in charge of all repairs, modifications and maintenance of equipment which includes: boats, barges, excavators and tractors.
          </p>
        </div>
        
        <div>
          <h3 class="gwm-header3">
            2012 - Present
          </h3>
          <p>
            Mobile Rig Welder of my current company Gonzalez Welding Mobile. I am in charge of all projects and provide great service for all customers.
          </p>
        </div>
        
      </div>
      <!-- End Well -->
      
    </div>
    <!-- End Work History Column -->   
  </div>
  <!-- End Work History -->
{% endblock %}

{% block script %}
<script>
  document.getElementById("about").className += " active";
</script>
{% endblock %}

pages/templates/pages/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" 
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">  

  <title>Gonzalez Welding - Bay Area Welding Contractor</title>

  <link rel="stylesheet" 
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">

  <link rel="stylesheet" 
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" 
        href="{% static 'css/gwm.css' %}">
  
  {% block link %}
  {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top navbar-lightlink">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navlinks">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="navbar-brand"> GWM </div>
    </div>

    <!-- Navigation Links -->
    <div class="collapse navbar-collapse" id="navlinks">
      <ul class="nav navbar-nav nav-pills">
        <li id="home">
          <a href="{% url 'pages:home' %}">Home</a>
        </li>
        <li id="about">
          <a href="{% url 'pages:about' %}">About</a>
        </li>
        <li id="work">
          <a href="{% url 'pages:work' %}">Work</a>
        </li>
        <li id="testimonials">
          <a href="{% url 'pages:testimonials' %}">Reviews</a>
        </li>
        <li id="contact">
          <a href="{% url 'pages:contact' %}">Contact</a>
        </li>
      </ul>
    </div>
    <!-- End Navigation Links -->

  </div>
</nav>
<!-- End Navigation -->

<!-- Content -->
<div class="text-center">

  <!-- Header -->
  <h1 class="gwm-header1">
    <span class="gwm-letter">G</span>onzalez
    <span class="gwm-letter">W</span>elding
    <span class="gwm-letter">M</span>obile
  </h1>

  <p class="gwm-header2">
    Mobile Welding Rig at your side. Anytime, Anyplace, almost Anything!
  </p>

  <!-- Temporarily Disable
  <button type="button" class="btn-circle">
    <i class="fa fa-2x fa-linkedin-square"></i>
  </button>
  -->
  <!-- End Header -->

  {% block content %}
  {% endblock %}

</div>
<!-- End Content -->

<!-- Footer -->
<div class="footer text-center">

  <p>Gonzalez Welding Mobile ©2017</p>
  <div>
    <a href="{% url 'pages:home'  %}">Home</a>
    <a href="{% url 'pages:about' %}">About</a>
    <a href="{% url 'pages:work'  %}">Work</a>
    <a href="{% url 'pages:testimonials' %}">Reviews</a>
    <a href="{% url 'pages:contact' %}">Contact</a>
  </div>

</div>
<!-- End Footer -->

<script src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
        crossorigin="anonymous">
</script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
</script>

{% block script %}
{% endblock %}

</body>
</html>

pages/templates/pages/contact.html
{% extends "pages/base.html" %}
{% load static %}

{% block content %}
  <!-- Contact & Map -->
  <div class="row gwm-mt gwm-mb gwm-text-left">

    <!-- Map -->
    <div class="col-md-5 col-md-offset-1" id="map-container">

      <h2 class="gwm-header2">
        <span class="gwm-letter">I</span>nformation
      </h2>

      <p>gwmcarlos@gonzalezwelding.com [(925) 550-6273]</p>
      <div class="gwm-map" id="map"></div>

    </div>
    <!-- End Map -->

    <!-- Contact -->
    <div class="col-md-5
                col-xs-12">

      <h2 class="gwm-header2">
        <span class="gwm-letter">C</span>ontact Us
      </h2>

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-info alert-dismissible">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

      {% if form.errors %}
        <div class="alert alert-warning alert-dismissible">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <strong>Warning!</strong> {{ form.errors }}
        </div>
      {% endif %}

      <form action="" method="post">

        {% for field in form %}

          <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
          </div>

        {% endfor %}

        {% csrf_token %}
        <input type="submit" class="btn btn-danger pull-right" value="Submit">
      </form>

    </div>
    <!-- End Contact -->

  </div>
  <!-- End Contact & Map -->
{% endblock %}

{% block script %}
<script>
  document.getElementById("contact").className += " active";
  function initMap() {

    var location = {lat: 37.965, lng: -121.696};
    var map = new google.maps.Map(document.getElementById('map'), {

      zoom: 14,
      center: location
    });

    var marker = new google.maps.Marker({

      position: location,
      map: map
    });
  }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUPIFJG_zsSGSP24m2VM1iND5nnWJUlUU&content_copy&callback=initMap">
</script>
{% endblock %}

pages/templates/pages/index.html
{% extends "pages/base.html" %}
{% load static %}

{% block content %}
  <div class="row gwm-mt">

    <div class="col-lg-5 col-lg-offset-2
                col-md-6 col-md-offset-1
                col-xs-10 col-xs-offset-1" >
      <p class="gwm-header3">
        <b> Professional Welding Since 1993 </b>
      </p>
    </div>

    <div class="col-md-2 col-md-offset-2
                col-xs-10 col-xs-offset-1">
      <p class="gwm-header3">
        <span class="gwm-letter">DBE CERTIFIED</span>
        <br> Firm Id #42711
      </p>
    </div>

  </div>

  <!-- Carousel -->
  <div class="row">

    <!-- Carousel Column -->
    <div class="col-lg-5 col-lg-offset-2
                col-md-6 col-md-offset-1
                col-xs-10 col-xs-offset-1">

      <!-- Carousel Outer -->
      <div id="myCarousel" class="carousel slide gwm-carousel" data-ride="carousel">

        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
          <li data-target="#myCarousel" data-slide-to="3"></li>
        </ol>

        <!-- Carousel Inner -->
        <div class="carousel-inner" role="listbox">

          <div class="item active">
            <img class="gwm-carousel-img" src="{% static 'images/merrygo1.jpg' %}">
          </div>

          <div class="item">
            <img class="gwm-carousel-img" src="{% static 'images/merrygo2.jpg' %}">
          </div>

          <div class="item">
            <img class="gwm-carousel-img" src="{% static 'images/merrygo3.jpg' %}">
          </div>

          <div class="item">
            <img class="gwm-carousel-img" src="{% static 'images/merrygo4.jpg' %}">
          </div>

        </div>
        <!-- End Carousel Inner -->

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>

        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
        <!-- End Controls -->

      </div>
      <!-- End Carousel Outer -->

    </div>
    <!-- End Carousel Column -->

    <div class="col-lg-3 col-lg-offset-0
                col-md-4 col-md-offset-0
                col-xs-8 col-xs-offset-2">
      <img class="img-responsive" src="{% static 'images/gwm_logo.png'%}">
    </div>

  </div>
  <!-- End Carousel -->

  <div class="row">
    <div class="col-lg-8  col-lg-offset-2
                col-md-10 col-md-offset-1">
      <p class="gwm-text gwm-mt">
        At Gonzalez Welding Mobile, we pride ourselves on our adaptability and versatility.
        Every blueprint we receive is treated as an opportunity to showcase our talent, innovation,
          and create lasting relationships with our clients and local contractors.
        We work closely with each and every one of our customers to ensure every detail is properly assessed and planned.
        Through this process, we are able to provide our customers with accurate estimates and realistic timeframes.
      </p>
    </div>
  </div>

  <a href="{% url 'pages:about' %}" class="btn btn-primary gwm-mb">
    Read More
  </a>

  <!-- Attribute Row -->
  <div class="row">
    <div class="col-lg-8  col-lg-offset-2
                col-md-10 col-md-offset-1">

      <!-- Inner Row -->
      <div class="row">

        <!-- Innovative Attribute -->
        <div class="col-md-4">
          <div class="panel panel-default gwm-panel">
            <div class="panel-heading">
              <i class="fa fa-wrench"></i> Innovative
            </div>
            <div class="panel-body gwm-text-left">
              GWM combines traditional and advance techniques to complete the toughest task at hand. No matter how big the problem GWM strives to find innovative solutions that meet the customers needs.
            </div>
          </div>
        </div>
        <!-- End Innovative Attribute -->

        <!-- Quality Attribute -->
        <div class="col-md-4">
          <div class="panel panel-default gwm-panel">
            <div class="panel-heading">
              <i class="fa fa-star"></i> Quality
            </div>
            <div class="panel-body gwm-text-left">
              Certified in Stick, Mig and Tig, GWM gurantees high quality welding services. All work is done to not just meet standards and expectations but surpass them.
            </div>
          </div>
        </div>
        <!-- End Quality Attribute -->

        <!-- Efficient Attribute -->
        <div class="col-md-4">
          <div class="panel panel-default gwm-panel">
            <div class="panel-heading">
              <i class="fa fa-handshake-o"></i> Efficient
            </div>
            <div class="panel-body gwm-text-left">
              GWM ensures it provides excellent customer service and efficient welding labor. The company prides itself in finishing all work in a timely manner while working along side the customers to meet deadlines.
            </div>
          </div>
        </div>
        <!-- End Efficient Attribute -->

      </div>
      <!-- End Inner Row -->

    </div>
  </div>
  <!-- End Attribute Row -->
{% endblock %}

{% block script %}
<script>
  document.getElementById("home").className += " active";
</script>
{% endblock %}

pages/templates/pages/testimonials.html
{% extends "pages/base.html" %}

{% block content %}
  <div class="row gwm-mt gwm-text-left">
    <div class="col-md-10 col-md-offset-1
                col-xs-10 col-xs-offset-1">

      <h2 class="gwm-header2">
        <span class="gwm-letter">R</span>eviews
      </h2>

      <div class="well gwm-well">
        <div class="row gwm-smt">

          Coming Soon
          {% for testimonial in testimonials %}
            <div class="col-md-6">
              <p class="gwm-text">{{ testimonial.text }}</p>
              <p class="">- {{ testimonial.quotee }}</p>
              <p class="">{{ testimonial.company }}</p>
            </div>
          {% endfor %}

        </div>
      </div>

    </div>
  </div>
{% endblock %}

{% block script %}
<script>
  document.getElementById("testimonials").className += " active";
</script>
{% endblock %}

pages/templates/pages/work.html
{% extends "pages/base.html" %}
{% load static %}

{% block link %}
  <link rel="stylesheet"
        href="{% static 'css/projects.css' %}"/>
  <link rel="stylesheet"
        href="{% static 'css/work.css' %}"/>
{%  endblock %}

{% block content %}

  {% with objects as projects %}
  {% if projects %}

    <!-- Display Projects -->
    <div class="projects">
    {% for project in projects %}

      <div class="project">

        <h3 class="gwm-text-left"> {{ project.title }} </h3>
        <p class="gwm-text-left"> {{ project.description }} </p>
        <br/>

        {% for image in project.images.all %}

          <div class="modal fade" id="{{ image.id }}" tabindex="-1">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span>&times;</span>
              </button>
            </div>
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <img  class="enlarged" src="{{ image.image_field.url }}"/>
              </div>
            </div>
          </div>

          <img class="preview" src="{{ image.image_field.url }}"
               data-toggle="modal" data-target="#{{ image.id }}"/>
        {% endfor %}

      </div>

    {% endfor %}
    </div>
    <!-- End Display Projects -->

    {% include 'subtemplates/pagination.html' %}

  {% endif %}
  {% endwith %}

{% endblock %}

{% block script %}
  <script>
    document.getElementById("work").className += " active";
  </script>
{% endblock %}