pages/urls.py
from django.conf.urls import url
from . import views

app_name = 'pages'
urlpatterns = [
    url(r'^$',              views.home,                name='index'),
    url(r'^home/$',         views.home,                name='home'),
    url(r'^about/$',        views.about,               name='about'),
    url(r'^contact/$',      views.contact,             name='contact'),
    url(r'^work/$',         views.work,                name='work'),
    url(r'^testimonials/$', views.testimonials,        name='testimonials')
]

projects/urls.py
from django.conf.urls import url
from . import views

app_name = 'projects'
urlpatterns = [
    url('^$', views.manage_projects, name="manager"),
    url('^create/$', views.create_project, name="create"),
    url('^modify/(?P<project_id>[0-9]{0,4})?$', views.modify_project, name="modify"),
    url('^delete/(?P<project_id>[0-9]{0,4})?$', views.delete_project, name="delete")
]

projects/models.py
from django.db import models


# Model for work/project information
class Project(models.Model):

    class Meta:
        ordering = ['-last_modified']

    title = models.CharField(unique=True, max_length=64)
    description = models.TextField(max_length=512)
    last_modified = models.DateTimeField(auto_now=True)
    public = models.BooleanField(default=True)

    def __str__(self):
        return 'Project: {}'.format(self.title)


# Linked to a project
class Image(models.Model):

    image_field = models.ImageField(upload_to="")
    project = models.ForeignKey(Project, related_name='images', on_delete=models.CASCADE)

    def __str__(self):
        return 'Image: {}'.format(self.image_field.url)

projects/forms.py
from django import forms
from projects.models import Project


class ProjectForm(forms.Form):

    title = forms.CharField(max_length=64)
    description = forms.CharField(widget=forms.Textarea, max_length=512, required=False)
    public = forms.BooleanField(initial=True, required=False)
    images = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    def clean_title(self):

        title = self.cleaned_data['title']
        project = Project.objects.filter(title=title)

        if project.exists():
            raise forms.ValidationError('Duplicate project title! Please choose a unique project title.')

        return title


class ModifyForm(ProjectForm):

    def __init__(self, project, *args, **kwargs):

        super(ModifyForm, self).__init__(*args, **kwargs)
        self.project = project

        # Set initial values for title/description and modify images requirement
        self.fields['title'].initial = project.title
        self.fields['description'].initial = project.description
        self.fields['public'].initial = project.public
        self.fields['images'].required = False

        # Create checkboxes for every image in the project
        self.create_checkboxes()

    def create_checkboxes(self):

        images = self.project.images.all()
        choices = []

        for i in range(len(images)):
            choices.append((images[i].id, ''))

        self.fields['checkboxes'] = \
            forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=choices)
        self.fields['checkboxes'].required = False

    def clean_title(self):

        title = self.cleaned_data['title']
        project = Project.objects.filter(title=title)

        # Only raise validation error if the project conflicts with other names and not its own
        if project.exists() and project[0].title != self.project.title:
            raise forms.ValidationError('Duplicate project title! Please choose a unique project title.')

        return title

projects/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import render
from common.utility import NoContentRedirect, HttpResponseSeeOther, render404, render_paginated
from projects.forms import ProjectForm, ModifyForm
from projects.models import Project
from projects.utility import get_project, handle_project_creation,\
    handle_project_modification, handle_project_deletion


# Render project manager
def manage_projects(request):
    return render_paginated(request, Project, 'projects/projectmanager.html', 'workbench/404.html')


# Create a project
def create_project(request):

    if request.POST:

        create_form = ProjectForm(request.POST, files=request.FILES)
        if create_form.is_valid():

            handle_project_creation(create_form)

            messages.success(request, "Project has been created")
            return HttpResponseSeeOther(reverse('projects:manager'))

    else:
        create_form = ProjectForm()

    # Return GET 200
    context = {'form': create_form}
    return render(request, 'projects/projectcreate.html', context)


# Modify a project
def modify_project(request, project_id):

    # Return 404 if project can not be found
    project = get_project(project_id)
    if not project:
        return render404(request, 'Project not found!', 'workbench/404.html')

    if request.POST:

        mod_form = ModifyForm(project, request.POST, files=request.FILES)
        if mod_form.is_valid():

            # Prevent multiple submissions
            if request.session.pop('modify', False):

                handle_project_modification(mod_form)
                messages.success(request, "Project changes have been saved")

            return HttpResponseSeeOther(reverse('projects:manager'))

    else:
        mod_form = ModifyForm(project)

    # Allow session to submit modify once
    request.session['modify'] = True

    # Return GET 200
    context = {'form': mod_form, 'project': project}
    return render(request, 'projects/projectmodify.html', context)


# Delete a project
def delete_project(request, project_id):

    # Return 404 if project can not be found
    project = get_project(project_id)
    if not project:
        return render404(request, 'Project not found!', 'workbench/404.html')

    # Handle delete request
    if request.method == "DELETE":

        handle_project_deletion(project)

        messages.success(request, "Project has been deleted")
        return NoContentRedirect(reverse('projects:manager'))

    # Return GET 200
    context = {'project': project}
    return render(request, 'projects/projectdelete.html', context)

projects/templates/projects/projectcreate.html
{% extends 'workbench/base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet"
        href="{% static 'css/workbenchform.css' %}"/>
  <link rel="stylesheet"
        href="{% static 'css/projectform.css' %}"/>
{% endblock %}

{% block content %}

  <h1> Create Project </h1>

  {% if form.errors %}

    <div class="alert alert-danger alert-dismissible alertwrapper">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      {{ form.title.errors }}
      {{ form.description.errors }}
      {{ form.images.errors }}
    </div>

  {% endif %}

  <form action="{% url 'projects:create' %}" id="projectform"
        method="post" enctype="multipart/form-data">

    {% csrf_token %}

    <div class="fieldwrapper">
      <label for="{{ form.title.id_for_label }}"> Project Title </label>
      <br/>
      {{ form.title }}
    </div>

    <div class="fieldwrapper">
      <label for="{{ form.description.id_for_label }}"> Description </label>
      <br/>
      {{ form.description }}
    </div>

    <div class="gwm-text-left fieldwrapper">
      <label for="{{ form.public.id_for_label }}"> Make Public: </label>
      {{ form.public }}
    </div>

    <div class="fieldwrapper">
      {{ form.images }}
    </div>

    <div class="submitwrapper">
      <a href="{% url 'projects:manager' %}" class="btn btn-warning" id="cancel"> Cancel </a>
      <input class="btn btn-success" type="submit" id="submit" value="Submit Project" />
    </div>

  </form>

{% endblock %}

{% block script %}
  <script src="{% static 'js/disableform.js' %}"></script>
{% endblock %}

projects/templates/projects/projectdelete.html
{% extends 'workbench/base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet"
        href="{% static 'css/workbenchform.css' %}"/>
  <link rel="stylesheet"
        href="{% static 'css/projectform.css' %}"/>
  <link rel="stylesheet"
        href="{% static 'css/projects.css' %}"/>
{% endblock %}

{% block content %}

  <h1> Delete <i>{{ project.title }}</i>? </h1>

    {% csrf_token %}

    <div class="fieldwrapper">
      <div class="project">

        <h3 class="align-left"> {{ project.title }} </h3>
        <p class="align-left"> {{ project.description }} </p>
        <br/>

        {% for image in project.images.all %}
          <img class="preview" src="{{ image.image_field.url }}"/>
        {% endfor %}

      </div>
    </div>

    <div class="submitwrapper">
      <a href="{% url 'projects:manager' %}" class="btn btn-success" id="cancel"> Cancel </a>
      <button class="btn btn-danger" id="delete"> Confirm Delete </button>
    </div>

{% endblock %}

{% block script %}
  <script src="{% static 'js/deleterequest.js' %}"></script>
{% endblock %}

projects/templates/projects/projectmanager.html
{% extends 'workbench/base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet"
        href="{% static 'css/projectmanager.css' %}"/>
  <link rel="stylesheet"
        href="{% static 'css/projects.css' %}"/>
{% endblock %}

{% block content %}

  <h1> Project Manager </h1>

  {% if messages %}

      <div class="alert alert-success alert-dismissible" id="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        {% for message in messages %}
          {{ message }}
        {% endfor %}
      </div>

  {% endif %}

  <div class="button-wrapper">
    <a href="{% url 'projects:create' %}" class="btn btn-success"> Create Project </a>
  </div>

  {% with objects as projects %}
  {% if not projects %}

    <h3>No projects available to view</h3>

  {% else %}

    <div class="projects">
    {% for project in projects %}

      <div class="project">

        <h3 class="gwm-text-left"> {{ project.title }} </h3>
        <p class="gwm-text-left"> {{ project.description }} </p>
        <br/>

        {% for image in project.images.all %}
          <img class="preview" src="{{ image.image_field.url }}"/>
        {% endfor %}

        <p class="gwm-text-left gwm-smt"> Last-Modified: {{ project.last_modified }} </p>
        <p class="gwm-text-left"> Public - {{ project.public }} </p>

        <div class="button-wrapper">
          <a href= "{% url 'projects:delete' %}{{ project.id }}" class="btn btn-danger"> Delete </a>
          <a href= "{% url 'projects:modify' %}{{ project.id }}" class="btn btn-primary"> Edit </a>
        </div>

      </div>

    {% endfor %}
    </div>

    {% include 'subtemplates/pagination.html' %}

  {% endif %}
  {% endwith %}

{% endblock %}

{% block script %}
  <script src="{% static 'js/alertdismiss.js' %}"></script>
{% endblock %}

projects/templates/projects/projectmodify.html
{% extends 'workbench/base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet"
        href="{% static 'css/workbenchform.css' %}"/>
  <link rel="stylesheet"
        href="{% static 'css/projectform.css' %}"/>
  <link rel="stylesheet"
        href="{% static 'css/projectmodify.css' %}"/>
{% endblock %}

{% block content %}

<h1>Editing <i>{{ project.title }}</i>!</h1>

  {% if form.errors %}
    <div class="alert alert-danger alert-dismissible alertwrapper">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      {{ form.title.errors }}
      {{ form.description.errors }}
      {{ form.images.errors }}
    </div>
  {% endif %}

  <form action="{% url 'projects:modify' %}{{ project.id }}" id="projectform"
        method="post" enctype="multipart/form-data" >

    {% csrf_token %}

    <div class="fieldwrapper">
      <label for="{{ form.title.id_for_label }}"> Project Title </label>
      <br/>
      {{ form.title }}
    </div>

    <div class="fieldwrapper">
      <label for="{{ form.description.id_for_label }}"> Description </label>
      <br/>
      {{ form.description }}
    </div>

    <div class="gwm-text-left fieldwrapper">
      <label for="{{ form.public.id_for_label }}"> Make Public: </label>
      {{ form.public }}
    </div>

    <div class="fieldwrapper">
      {{ form.images }}
    </div>

    <div class="fieldwrapper">
      {% for checkbox in form.checkboxes %}
        {{ checkbox }}
      {% endfor %}
    </div>

    <div class="submitwrapper">
      <a href="{% url 'projects:manager' %}" class="btn btn-warning" id="cancel"> Cancel </a>
      <input class="btn btn-success" type="submit" id="submit" value="Save Changes" />
    </div>

  </form>

{% endblock %}

{% block script %}

  <script>

      // Attach images to checkboxes

      var images = [];
      {% for image in project.images.all %}
          images.push("{{ image.image_field.url }}");
      {% endfor %}

      images.forEach(function(url, index) {

          var label = document.querySelector("[for='id_checkboxes_" + index + "']");
          label.insertAdjacentHTML("beforeend", "<img src='" + images[index] + "'/>");
      });

  </script>

  <script src="{% static 'js/disableform.js' %}"></script>

{% endblock %}