pages/urls.py
from django.conf.urls import url
from . import views

app_name = 'pages'
urlpatterns = [
    url(r'^$',              views.home,                name='index'),
    url(r'^home/$',         views.home,                name='home'),
    url(r'^about/$',        views.about,               name='about'),
    url(r'^contact/$',      views.contact,             name='contact'),
    url(r'^work/$',         views.work,                name='work'),
    url(r'^testimonials/$', views.testimonials,        name='testimonials')
]

projects/urls.py
from django.conf.urls import url
from . import views

app_name = 'projects'
urlpatterns = [
    url('^$', views.manage_projects, name="manager"),
    url('^create/$', views.create_project, name="create"),
    url('^modify/(?P<project_id>[0-9]{0,4})?$', views.modify_project, name="modify"),
    url('^delete/(?P<project_id>[0-9]{0,4})?$', views.delete_project, name="delete")
]

workbench/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'workbench'
urlpatterns = [
    url('^$', views.workbench, name='workbench'),
    url('^login/$', views.login_view, name='login'),
    url('^logout/$', views.logout_view, name='logout')
]

workbench/models.py
from django.db import models

workbench/forms.py
from django import forms


class LoginForm(forms.Form):

    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput(), max_length=128)

workbench/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from workbench.forms import LoginForm


# Render workbench home
def workbench(request):

    return HttpResponseRedirect(reverse('projects:manager'), status=307)
    # return render(request, 'workbench/home.html')


# Login page
def login_view(request):

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('workbench:workbench'))

    if request.POST:

        login_form = LoginForm(request.POST)
        if login_form.is_valid():

            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user:

                login(request, user)
                return HttpResponseRedirect(reverse('projects:manager'))

            messages.error(request, 'Invalid username and/or password')

    else:
        login_form = LoginForm()

    context = {'form': login_form}
    return render(request, 'workbench/login.html', context)


# Logout view
def logout_view(request):

    if request.user.is_authenticated:
        logout(request)

    return HttpResponseRedirect(reverse('workbench:login'))

workbench/templates/workbench/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

  <title>GWM Workbench</title>

  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">

  <link rel="stylesheet"
        href="{% static 'css/gwm.css' %}">

  {% block link %}
  {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top navbar-lightlink">
  <div class="container-fluid">

    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navlinks">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>

      <div class="navbar-brand">
          <a href="{% url 'pages:home' %}">GWM</a>
      </div>

    </div>

    <!-- Navigation Links -->
    <div class="collapse navbar-collapse" id="navlinks">

      <ul class="nav navbar-nav nav-pills">

        <!--
        <li id="home">
          <a href="{% url 'workbench:workbench' %}">Workbench</a>
        </li>
        -->

        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            Projects
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'projects:manager'%}"> Manage Projects </a></li>
            <li><a href="{% url 'projects:create' %}"> Create Project </a></li>
          </ul>
        </li>

        <!--
        <li id="reviews">
          <a>Reviews</a>
        </li>
        -->

      </ul>

      {% if request.user.is_authenticated %}
        <ul class="nav navbar-nav nav-pills navbar-right">

          <li id="logout">
            <a href="{% url 'workbench:logout' %}"> Logout </a>
          </li>

        </ul>
      {% endif %}

    </div>
    <!-- End Navigation Links -->

  </div>
</nav>
<!-- End Navigation -->

<!-- Content -->
<div class="text-center">

  <!-- Header -->
  <h1 class="gwm-header1">
    <span class="gwm-letter">G</span>WM
    <span class="gwm-letter">W</span>orkbench
  </h1>

  {% block content %}
  {% endblock %}

</div>
<!-- End Content -->

<!-- Footer -->
<div class="footer text-center">
  <p>Gonzalez Welding Mobile ©2017</p>
</div>
<!-- End Footer -->

<script src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
        crossorigin="anonymous">
</script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
</script>

{% block script %}
{% endblock %}

</body>
</html>

workbench/templates/workbench/createproject.html
{% extends 'workbench/base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet"
        href="{% static 'css/projectforms.css' %}"/>
{% endblock %}

{% block content %}

  <h1> Create Project </h1>

  {% if form.errors %}

    <div class="alert alert-danger alert-dismissible alertwrapper">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      {{ form.title.errors }}
      {{ form.description.errors }}
      {{ form.images.errors }}
    </div>

  {% endif %}

  <form action="{% url 'workbench:createproject' %}" id="projectform"
        method="post" enctype="multipart/form-data">

    {% csrf_token %}

    <div class="fieldwrapper">
      <label for="{{ form.title.id_for_label }}"> Project Title </label>
      <br/>
      {{ form.title }}
    </div>

    <div class="fieldwrapper">
      <label for="{{ form.description.id_for_label }}"> Description </label>
      <br/>
      {{ form.description }}
    </div>

    <div class="fieldwrapper">
      {{ form.images }}
    </div>

    <div class="submitwrapper">
      <a href="{% url 'workbench:manageprojects' %}" class="btn btn-warning" id="cancel"> Cancel </a>
      <input class="btn btn-success" type="submit" id="submit" value="Submit Project" />
    </div>

  </form>

{% endblock %}

{% block script %}
  <script src="{% static 'js/disablebuttons.js' %}">
  </script>
{% endblock %}

workbench/templates/workbench/deleteproject.html
{% extends 'workbench/base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet"
        href="{% static 'css/projectforms.css' %}"/>
  <link rel="stylesheet"
        href="{% static 'css/projects.css' %}"/>
{% endblock %}

{% block content %}

  <h1> Delete <i>{{ project.title }}</i>? </h1>

  <form action="{% url 'workbench:deleteproject' %}{{ project.id }}" method="post" id="projectform">

    {% csrf_token %}

    <div class="fieldwrapper">
      <div class="project">

        <h3 class="align-left"> {{ project.title }} </h3>
        <p class="align-left"> {{ project.description }} </p>
        <br/>

        {% for image in project.images.all %}
          <img class="preview" src="{{ image.image_field.url }}"/>
        {% endfor %}

      </div>
    </div>

    <div class="submitwrapper">
      <a href="{% url 'workbench:manageprojects' %}" class="btn btn-success" id="cancel"> Cancel </a>
      <input class="btn btn-danger" type="submit" id="submit" value="Confirm Delete"/>
    </div>

  </form>

{% endblock %}

{% block script %}
  <script src="{% static 'js/disablebuttons.js' %}">
  </script>
{% endblock %}

workbench/templates/workbench/home.html
{% extends 'workbench/base.html' %}

{% block content %}
  <h1> Workbench Home </h1>
{% endblock %}

workbench/templates/workbench/login.html
{% extends 'workbench/base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet"
        href="{% static 'css/workbenchform.css' %}"/>
  <link rel="stylesheet"
        href="{% static 'css/login.css' %}"/>
{% endblock %}

{% block content %}

  <h1> Login Required </h1>

  {% if messages %}

      <div class="alert alert-danger alert-dismissible alertwrapper" id="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        {% for message in messages %}
          {{ message }}
        {% endfor %}
      </div>

  {% endif %}

  <form action="{% url 'workbench:login' %}" method="post">

    {% csrf_token %}

    <div class="fieldwrapper">
      <label for="{{ form.username.id_for_label }}"> Username </label>
      <br/>
      {{ form.username }}
    </div>

    <div class="fieldwrapper">
      <label for="{{ form.password.id_for_label }}"> Password </label>
      <br/>
      {{ form.password }}
    </div>

    <div class="submitwrapper">
      <input class="btn btn-primary" type="submit" value="Login" />
    </div>

  </form>

{% endblock %}

workbench/templates/workbench/manageprojects.html
{% extends 'workbench/base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet"
        href="{% static 'css/manageprojects.css' %}"/>
  <link rel="stylesheet"
        href="{% static 'css/projects.css' %}"/>
{%  endblock %}

{% block content %}

  <h1> Project Manager </h1>

  {% if messages %}

      <div class="alert alert-success alert-dismissible" id="alert">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        {% for message in messages %}
          {{ message }}
        {% endfor %}
      </div>

  {% endif %}

  <div class="button-wrapper">
    <a href="{% url 'workbench:createproject' %}" class="btn btn-success"> Create Project </a>
  </div>

  {% if projects %}

    <div class="projects">
    {% for project in projects %}

      <div class="project">

        <h3 class="gwm-text-left"> {{ project.title }} </h3>
        <p class="gwm-text-left"> {{ project.description }} </p>
        <br/>

        {% for image in project.images.all %}
          <img class="preview" src="{{ image.image_field.url }}"/>
        {% endfor %}

        <div class="button-wrapper">
          <a href= "{% url 'workbench:deleteproject' %}{{ project.id }}" class="btn btn-danger"> Delete </a>
          <a href= "{% url 'workbench:modifyproject' %}{{ project.id }}" class="btn btn-primary"> Edit </a>
        </div>

      </div>

    {% endfor %}
    </div>

  {% else %}

    <h3>No projects available to view</h3>

  {% endif %}

{% endblock %}

{% block script %}
  <script src="{% static 'js/alertdismiss.js' %}">
  </script>
{% endblock %}

workbench/templates/workbench/modifyproject.html
{% extends 'workbench/base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet"
        href="{% static 'css/modifyproject.css' %}"/>
  <link rel="stylesheet"
        href="{% static 'css/projectforms.css' %}"/>
{% endblock %}

{% block content %}

<h1>Editing <i>{{ project.title }}</i>!</h1>

  {% if form.errors %}
    <div class="alert alert-danger alert-dismissible alertwrapper">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      {{ form.title.errors }}
      {{ form.description.errors }}
      {{ form.images.errors }}
    </div>
  {% endif %}

  <form action="{% url 'workbench:modifyproject' %}{{ project.id }}" id="projectform"
        method="post" enctype="multipart/form-data" >

    {% csrf_token %}

    <div class="fieldwrapper">
      <label for="{{ form.title.id_for_label }}"> Project Title </label>
      <br/>
      {{ form.title }}
    </div>

    <div class="fieldwrapper">
      <label for="{{ form.description.id_for_label }}"> Description </label>
      <br/>
      {{ form.description }}
    </div>

    <div class="fieldwrapper">
      {{ form.images }}
    </div>

    <div class="fieldwrapper">
      {% for checkbox in form.checkboxes %}
        {{ checkbox }}
      {% endfor %}
    </div>

    <div class="submitwrapper">
      <a href="{% url 'workbench:manageprojects' %}" class="btn btn-warning" id="cancel"> Cancel </a>
      <input class="btn btn-success" type="submit" id="submit" value="Save Changes" />
    </div>

  </form>

{% endblock %}

{% block script %}

  <script>

      // Attach images to checkboxes

      var images = [];
      {% for image in project.images.all %}
      images.push("{{ image.image_field.url }}");
      {% endfor %}

      images.forEach(function(url, index) {

          var label = document.querySelector("[for='id_checkboxes_" + index + "']");
          label.insertAdjacentHTML("beforeend", "<img src='" + images[index] + "'/>");
      });

  </script>

  <script src="{% static 'js/disablebuttons.js' %}">
  </script>

{% endblock %}

workbench/templates/workbench/newproject.html
{% extends 'workbench/base.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet"
      href="{% static 'css/projectforms.css' %}"/>
{% endblock %}

{% block content %}

  {% if form.errors %}
    <div class="alert alert-danger alert-dismissible alertwrapper">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      {{ form.title.errors }}
      {{ form.description.errors }}
      {{ form.images.errors }}
    </div>
  {% endif %}

  <form action="{% url 'workbench:newproject' %}" method="post" enctype="multipart/form-data">

    {% csrf_token %}

    <div class="fieldwrapper">
      <label for="{{ form.title.id_for_label }}">Project Title</label>
      <br/>
      {{ form.title }}
    </div>

    <div class="fieldwrapper">
      <label for="{{ form.description.id_for_label }}">Description</label>
      <br/>
      {{ form.description }}
    </div>

    <div class="fieldwrapper">
      {{ form.images }}
    </div>

    <div class="submitwrapper">
      <a href="{% url 'workbench:manageprojects' %}" class="btn btn-warning">Cancel</a>
      <input class="btn btn-success" type="submit" value="Submit Project" />
    </div>

  </form>
{% endblock %}